spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: password
    database: db
    driverClassname: org.postgresql.Driver